---
- name: Full configuration of the Challenge server
  hosts: testservers
  become: yes
  become_method: sudo

- include: python2.yml
- include: node_app.yml
- include: nginx_tls_proxyreverse.yml
- include: add_parser_cron.yml