---
# Based and modified from: Ansible Up and Running
- name: Configure webserver with nginx and tls
  hosts: testservers
  become: yes
  become_method: sudo
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  tasks:
    - name: Install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600

    - name: create directories for TLS certificates
      file: path=/etc/nginx/ssl state=directory

    - name: copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: Start APP
      sudo_user: ubuntu
      command: {{ item }}
      with_items:
        - systemctl enable nginx.service
        - systemctl daemon-reload
        - systemctl restart nginx.service
      ignore_errors: yes

    - name: Listen on 1.2.3.4
      lineinfile: dest=/etc/systemd/system/multi-user.target.wants/nginx.service
                  line="Restart=always"
                  insertafter="[Service]"

    - name: enable configuration
      file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted